# Generated by Django 6.0.2 on 2026-02-26 13:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('os_number', models.CharField(max_length=20)),
                ('problem_description', models.TextField(max_length=1024)),
                ('status', models.CharField(choices=[('opened', 'Aberta'), ('in_progress', 'Em andamento'), ('concluded', 'Concluída'), ('canceled', 'Cancelada')], default='opened')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='low')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('closed_date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='clients.client')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to='technicians.technician')),
            ],
        ),
    ]
