# Generated by Django 6.0.2 on 2026-02-26 13:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=256)),
                ('active', models.BooleanField(default=False)),
                ('hiring_date', models.DateTimeField()),
            ],
        ),
    ]
