# Generated by Django 6.0.2 on 2026-02-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='email',
            field=models.EmailField(max_length=256, unique=True),
        ),
    ]
