# Generated by Django 6.0.2 on 2026-02-26 13:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=512)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='service_orders.serviceorder')),
            ],
        ),
    ]
